const path = require('path');
const sqlite3 = require('sqlite3').verbose();

const databasePath = path.resolve(__dirname, '../Data/Commercial/commercial_properties_database.db');

const db = new sqlite3.Database(databasePath);

db.run('PRAGMA foreign_keys=off;');

db.run('BEGIN TRANSACTION;');

db.run(`
  CREATE TABLE IF NOT EXISTS commercial_properties_table (
    'MLS' TEXT PRIMARY KEY,
    'TimestampSql',
    'PhotoCount',
    'PhotoLink' JSON,
    'MinListPrice',
    'MaxListPrice',
    'SearchAddress',
    'ExpensesActualEstimated',
    'Extras',
    'FinancialStatement',
    'Franchise',
    'Freestanding',
    'LotFront',
    'GarageType',
    'GrossIncomeSales',
    'HeatExpenses',
    'HeatType',
    'HoursOpen',
    'HydroExpense',
    'IndustrialArea',
    'IndustrialAreaCode',
    'InsuranceExpense',
    'EstimInventoryValuesAtCost',
    'LotIrregularities',
    'LegalDescription',
    'LLBO',
    'LotBldgUnitCode',
    'LotSizeCode',
    'ListPriceCode',
    'ListPrice',
    'Maintenance',
    'ManagementExpense',
    'MinimumRentalTerm',
    'MapColumn',
    'Map',
    'MapRow',
    'NetIncomeBeforeDebt',
    'OfficeAptArea',
    'PossessionRemarks',
    'Occupancy',
    'OfficeAptAreaCode',
    'OperatingExpenses',
    'OtherExpenses',
    'OutsideStorage',
    'OutofAreaMunicipality',
    'ParcelId',
    'ParkingSpaces',
    'PerBuilding',
    'AirConditioning',
    'RemarksForClients',
    'Address',
    'Amps',
    'AptUnit',
    'AreaInfluences1',
    'AreaInfluences2',
    'AssessmentYear',
    'Washrooms',
    'BaySizeWidthFeet',
    'BaySizeWidthInches',
    'BaySizeLengthFeet',
    'BaySizeLengthInches',
    'Basement1',
    'Use',
    'ClearHeightFeet',
    'ClearHeightInches',
    'Chattels',
    'CommonAreaUpcharge',
    'CommercialCondoFees',
    'Province',
    'Crane',
    'DirectionsCrossStreets',
    'DaysOpen',
    'BusinessBuildingName',
    'LotDepth',
    'DisplayAddressOnInternet',
    'Elevator',
    'Employees',
    'Seats',
    'Sewers',
    'DriveInLevelShippingDoorsHeightFeet',
    'DriveInLevelShippingDoorsHeightInches',
    'DriveInLevelShippingDoors',
    'DriveInLevelShippingDoorsWidthFeet',
    'DriveInLevelShippingDoorsWidthInches',
    'DoubleManShippingDoorsHeightFeet',
    'DoubleManShippingDoorsHeightInches',
    'DoubleManShippingDoors',
    'DoubleManShippingDoorsWidthFeet',
    'DoubleManShippingDoorsWidthInches',
    'GradeLevelShippingDoorsHeightFeet',
    'GradeLevelShippingDoorsHeightInches',
    'GradeLevelShippingDoors',
    'GradeLevelShippingDoorsWidthFeet',
    'GradeLevelShippingDoorsWidthInches',
    'TruckLevelShippingDoorsHeightFeet',
    'TruckLevelShippingDoorsHeightInches',
    'TruckLevelShippingDoors',
    'TruckLevelShippingDoorsWidthFeet',
    'TruckLevelShippingDoorsWidthInches',
    'SoilTest',
    'Sprinklers',
    'StreetName',
    'StreetDirection',
    'Street',
    'StreetAbbreviation',
    'Status',
    'Survey',
    'Taxes',
    'TaxesExpense',
    'MaximumRentalTerm',
    'TotalArea',
    'TotalAreaCode',
    'VirtualTourURL',
    'CommunityCode',
    'AreaCode',
    'TrailerParkingSpots',
    'Assessment',
    'TypeOwnSrch',
    'TypeOwn1Out',
    'TypeTaxes',
    'Uffi',
    'Utilities',
    'VacancyAllowance',
    'SellerPropertyInfoStatement',
    'Volts',
    'VirtualTourUploadDate',
    'Water',
    'WaterExpense',
    'WaterSupplyTypes',
    'TaxYear',
    'ApproxAge',
    'YearExpenses',
    'PostalCode',
    'Zoning',
    'MunicipalityDistrict',
    'MunicipalityCode',
    'Municipality',
    'IdxUpdtedDt',
    'PixUpdtedDt',
    'PercentageRent',
    'Category',
    'Rail',
    'RetailArea',
    'RetailAreaCode',
    'ListBrokerage',
    'SaleLease',
    'Area',
    'Community'
  )
`);

db.run('COMMIT;', () => {
  db.close();
});